title: Madhusudhan B N # your name (or website title) here
logo: "/images/madhusudhanbn.png?raw=true" # photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Associate Vice President - Cloud & DevOps Practice at Kotak Securities ✨ | AWS Kubernetes Terraform Ansible 🔥 | Cloud Security, DevSecOps, FinOps ⛅ | 
<br><br>
Kotak Neo - Building cutting-edge platform for digital investing 🚀
  <br><br>
  <a href="https://www.linkedin.com/in/madhusudhanbn/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
