title: Madhusudhan B N # your name (or website title) here
logo: "/images/madhusudhanbn.png?raw=true" # photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Solutions Architect - Cloud & DevOps Engineering | IoT & Smart Products | AWS GCP Azure MLOps K8s IaC 
  <br><br>
  Helping customers to build, thrive and optimize on Cloud
  <br><br>
  <a href="https://www.linkedin.com/in/madhusudhanbn/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
